services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "9132"
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - "9131"
    depends_on:
      - backend

  db:
    image: nouchka/sqlite3
    volumes:
      - ./server/db:/db

