services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9132:9132"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "9131:9131"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - backend
  db:
    image: nouchka/sqlite3
    volumes:
      - ./server/db:/db
